<?php
session_start();
require_once '../config.php';
require_once '../includes/system_functions.php';
require_once '../includes/logger.php';

// Check session timeout
checkSessionTimeout();

// Check if user is logged in
if (!isset($_SESSION['logged_in']) || $_SESSION['logged_in'] !== true) {
    http_response_code(401);
    echo json_encode(['error' => 'Unauthorized']);
    exit();
}

// Check if user has correct role
if ($_SESSION['role'] !== 'office_admin') {
    http_response_code(403);
    echo json_encode(['error' => 'Forbidden']);
    exit();
}

header('Content-Type: application/json');

try {
    // Create temporary directory for export
    $temp_dir = sys_get_temp_dir() . '/pims_export_' . $_SESSION['user_id'] . '_' . time();
    mkdir($temp_dir, 0755, true);
    
    // Export user profile data
    $profile_data = [
        'user_id' => $_SESSION['user_id'],
        'email' => $_SESSION['email'],
        'first_name' => $_SESSION['first_name'],
        'last_name' => $_SESSION['last_name'],
        'role' => $_SESSION['role'],
        'office_id' => $_SESSION['office_id'],
        'export_date' => date('Y-m-d H:i:s'),
        'export_type' => 'user_data_export'
    ];
    
    file_put_contents($temp_dir . '/profile.json', json_encode($profile_data, JSON_PRETTY_PRINT));
    
    // Export user activity logs (last 90 days)
    $activity_query = "SELECT * FROM system_logs WHERE user_id = ? AND created_at >= DATE_SUB(NOW(), INTERVAL 90 DAY) ORDER BY created_at DESC";
    $stmt = $conn->prepare($activity_query);
    $stmt->bind_param("i", $_SESSION['user_id']);
    $stmt->execute();
    $result = $stmt->get_result();
    
    $activities = [];
    while ($row = $result->fetch_assoc()) {
        $activities[] = $row;
    }
    
    file_put_contents($temp_dir . '/activity_logs.json', json_encode($activities, JSON_PRETTY_PRINT));
    
    // Export user's requests (last 90 days)
    $requests_query = "SELECT * FROM requests WHERE user_id = ? AND created_at >= DATE_SUB(NOW(), INTERVAL 90 DAY) ORDER BY created_at DESC";
    $stmt = $conn->prepare($requests_query);
    $stmt->bind_param("i", $_SESSION['user_id']);
    $stmt->execute();
    $result = $stmt->get_result();
    
    $requests = [];
    while ($row = $result->fetch_assoc()) {
        $requests[] = $row;
    }
    
    file_put_contents($temp_dir . '/requests.json', json_encode($requests, JSON_PRETTY_PRINT));
    
    // Export user's borrow requests (last 90 days)
    $borrow_requests_query = "SELECT br.*, o.name as office_name FROM borrow_requests br 
                             LEFT JOIN offices o ON br.requested_by_office = o.id 
                             WHERE br.requested_by_office = ? AND br.created_at >= DATE_SUB(NOW(), INTERVAL 90 DAY) 
                             ORDER BY br.created_at DESC";
    $stmt = $conn->prepare($borrow_requests_query);
    $stmt->bind_param("i", $_SESSION['office_id']);
    $stmt->execute();
    $result = $stmt->get_result();
    
    $borrow_requests = [];
    while ($row = $result->fetch_assoc()) {
        $borrow_requests[] = $row;
    }
    
    file_put_contents($temp_dir . '/borrow_requests.json', json_encode($borrow_requests, JSON_PRETTY_PRINT));
    
    // Create README file
    $readme_content = "
# User Data Export

This archive contains your personal data from PIMS.

## Files Included:

- **profile.json**: Your basic profile information
- **activity_logs.json**: Your system activity logs (last 90 days)
- **requests.json**: Your requests and transactions (last 90 days)
- **borrow_requests.json**: Borrow requests made by your office (last 90 days)

## Export Information:

- Export Date: " . date('Y-m-d H:i:s') . "
- User ID: " . $_SESSION['user_id'] . "
- Email: " . $_SESSION['email'] . "
- Export Type: User Data Export (GDPR Compliance)

## Data Retention:

This export contains data from the last 90 days only. For complete historical data, please contact your system administrator.

## Privacy:

This data is provided under GDPR compliance regulations. Please keep it secure and delete when no longer needed.

Generated by PIMS (Property and Inventory Management System)
";
    
    file_put_contents($temp_dir . '/README.txt', $readme_content);
    
    // Create ZIP archive
    $zip_file = $temp_dir . '.zip';
    $zip = new ZipArchive();
    
    if ($zip->open($zip_file, ZipArchive::CREATE | ZipArchive::OVERWRITE) === TRUE) {
        // Add all files to ZIP
        $files = glob($temp_dir . '/*');
        foreach ($files as $file) {
            if (is_file($file)) {
                $zip->addFile($file, basename($file));
            }
        }
        $zip->close();
        
        // Clean up temporary directory
        $files = glob($temp_dir . '/*');
        foreach ($files as $file) {
            unlink($file);
        }
        rmdir($temp_dir);
        
        // Serve ZIP file
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="my_data_export_' . date('Y-m-d') . '.zip"');
        header('Content-Length: ' . filesize($zip_file));
        header('Cache-Control: no-cache, must-revalidate');
        header('Pragma: no-cache');
        
        readfile($zip_file);
        
        // Clean up ZIP file
        unlink($zip_file);
        
        // Log export action
        logSystemAction($_SESSION['user_id'], 'export', 'user_data', 'User exported their personal data');
        
        exit();
    } else {
        throw new Exception('Failed to create ZIP archive');
    }
    
} catch (Exception $e) {
    error_log("User data export error: " . $e->getMessage());
    http_response_code(500);
    echo json_encode(['error' => 'Failed to export data: ' . $e->getMessage()]);
}
?>
